# Site settings
title: tktechie studios
email: <SCRIPT TYPE="text/javascript"> emailE=('tim'); emailE=(emailE + '@'); emailE=(emailE + 'tktechie.me'); document.write('<a href="mailto:' + emailE + '">'+ emailE + '</a>') </SCRIPT>
description: > # this means to ignore newlines until "baseurl:"
  I'm a technology oriented person interested in learning about almost everything. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tktechie.me" # the base hostname & protocol for your site
twitter_username: tktechie
github_username:  tktechie

menu:
- {name: About Me, url: '/index.html#about'}
#- {name: Posts, url: '/index.html#posts'}
#- {name: Clients, url: '#clients'}
- {name: Contact, url: '/index.html#contact'}

blurb: >
  Hi there!

skills:
- {name: 3D Modeling, value: '8'}
- {name: Photo Realistic Renders, value: '7'}
- {name: Learning, value: '7'}
- {name: Teaching, value: '7'}
- {name: Planning, value: '5'}
- {name: Visual Design, value: '5'}
- {name: UX Design, value: '3'}
- {name: Programming, value: '3'}

kramdown:
  input: GFM